---
verbose: false
concurrency: 10
pidfile: ./tmp/pids/sidekiq.pid
logfile: ./log/sidekiq.log
queues:
  - default
  - cinemas_manage_system_production_default
production:
  concurrency: 25
staging:
  concurrency: 15
